### PR TITLE
33 new icons for gen2

### PR DESCRIPTION
**Pull request by BadiBasso**
Changes
-------
-33 new icons for Gen2 pokemons.

Other informations
------------------
Icons retrieved from pokemongo.wikia.com. Originally extracted from official client screenshots or similar.
This PR can be left waiting. I will update when more icons become available.

### CODE REVIEW

**Comment by mtaheij** [comment]
Reopening as the assets in the 3d pack that I downloaded contains images that are sized according to the real-life size of the pokemons. Small pokemons appear very small on the map.

**Comment by BadiBasso** [comment]
Look quite rough in capture, but better in other screens.

**Comment by BadiBasso** [comment]
I have code ready to show different genders and costumes.in Inventory. Needs these 3d assets though.
wp_ss_20170228_0001

**Comment by BadiBasso** [comment]
pokemongo.wikia.com now has quite nice icons for all Gen2 mons. But they don't have icons for different genders or shinies.
What about using small icons from 3d pack in pokemon list and detail pages and wikia icons in dex, map and capture?

**Pull request closed without merging**
