### PR TITLE
Update pogolib

### PR DESCRIPTION
**Pull request by Furtif**

### CODE REVIEW

**Comment by Furtif** [comment]
i thinks here banned on discord server....

**Comment by Furtif** [comment]
@mtaheij revise last commit affter merge

**Comment by mtaheij** [comment]
Hi @Furtif,
I think it's best if you take over this project. There is simply no time for me to keep up and create new versions for each commit you make. Besides that, I hardly play the game anymore.

**Comment by Rover656** [comment]
@Furtif, if you'd like someone to work with, I'd be happy to help out, I'm currently working on a rewrite of pogo with cleaned UI etc. and clean code (pogo had become extremely messy due to the amount of contributors.) and so I believe this time pogo should have a "team" in the form of a github organisation in order to have good support for the program. I can understand if you'd like to take this on alone, but I'll leave the offer there. Bye!

**Pull request merged**
